from .Customer_serializer import CustomerSerializer,Cust_and_bookingsSerializer
from .Service_serializer import ServiceSerializer
from .Booking_serializer import BookingSerializer,BookingSerializerPost
from .Payment_serializer import PaymentSerializer,PaymentSerializerPost