# Generated by Django 5.1.4 on 2025-01-06 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=150, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('car_model', models.CharField(blank=True, max_length=100)),
                ('car_number', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'db_table': 'CarWash_customer',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration', models.DurationField()),
            ],
            options={
                'db_table': 'CarWash_service',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('status', models.CharField(choices=[('pending', 'Очікування'), ('accepted', 'Прийнято'), ('In procces', 'В процесі'), ('completed', 'Готово')], default='pending', max_length=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WetCar.customer')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WetCar.service')),
            ],
            options={
                'db_table': 'CarWash_booking',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Очікування оплати'), ('completed', 'Оплата пройдена'), ('failed', 'Помилка оплати')], default='pending', max_length=10)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='WetCar.booking')),
            ],
        ),
    ]
