# Generated by Django 5.1.4 on 2025-02-02 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WetCar', '0007_alter_booking_car_brand_alter_booking_car_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='WetCar.service'),
        ),
    ]
