# Generated by Django 5.1.4 on 2025-02-02 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WetCar', '0008_alter_booking_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='car_brand',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
