# Generated by Django 5.1.4 on 2025-02-02 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WetCar', '0010_alter_booking_car_number_alter_booking_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
