# Generated by Django 5.1.4 on 2025-02-02 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WetCar', '0011_alter_booking_date_alter_booking_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
